from __future__ import annotations

import pathlib
import tomllib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
DESKTOP = ROOT / "apps" / "desktop"
PNPM_LOCK = DESKTOP / "pnpm-lock.yaml"
CARGO_TOML = DESKTOP / "src-tauri" / "Cargo.toml"
CARGO_LOCK = DESKTOP / "src-tauri" / "Cargo.lock"
BUILD_WORKFLOW = ROOT / ".github" / "workflows" / "desktop-build.yml"
ACCEPTANCE_WORKFLOW = ROOT / ".github" / "workflows" / "desktop-acceptance.yml"
RELEASE_WORKFLOW = ROOT / ".github" / "workflows" / "desktop-release.yml"


class DesktopDependencyLockingTests(unittest.TestCase):
    def setUp(self) -> None:
        self.workflows = {
            "build": BUILD_WORKFLOW.read_text(encoding="utf-8"),
            "acceptance": ACCEPTANCE_WORKFLOW.read_text(encoding="utf-8"),
            "release": RELEASE_WORKFLOW.read_text(encoding="utf-8"),
        }

    def test_real_dependency_lockfiles_are_committed(self) -> None:
        pnpm = PNPM_LOCK.read_text(encoding="utf-8")
        cargo = CARGO_LOCK.read_text(encoding="utf-8")
        self.assertIn("lockfileVersion: '9.0'", pnpm)
        self.assertIn("'@tauri-apps/cli':", pnpm)
        self.assertIn("# This file is automatically @generated by Cargo.", cargo)
        self.assertIn('name = "divan-desktop"', cargo)
        self.assertIn('name = "tauri"', cargo)

    def test_cargo_manifest_dependencies_are_bound_in_root_lock_package(self) -> None:
        with CARGO_TOML.open("rb") as stream:
            manifest = tomllib.load(stream)
        with CARGO_LOCK.open("rb") as stream:
            lock = tomllib.load(stream)

        root = next(
            package
            for package in lock["package"]
            if package["name"] == manifest["package"]["name"]
        )
        locked_dependencies = {
            dependency.split(" ", 1)[0] for dependency in root.get("dependencies", [])
        }
        declared_dependencies = set(manifest.get("dependencies", {})) | set(
            manifest.get("build-dependencies", {})
        )
        self.assertEqual(
            declared_dependencies - locked_dependencies,
            set(),
            "Cargo.toml declares dependencies missing from the root Cargo.lock package; "
            "regenerate Cargo.lock with Cargo before committing",
        )

    def test_every_windows_lane_uses_frozen_pnpm_resolution(self) -> None:
        for name, text in self.workflows.items():
            with self.subTest(workflow=name):
                self.assertIn("pnpm install --frozen-lockfile", text)
                self.assertNotIn("pnpm install --no-frozen-lockfile", text)

    def test_every_windows_lane_enforces_cargo_lock(self) -> None:
        for name, text in self.workflows.items():
            with self.subTest(workflow=name):
                self.assertRegex(
                    text,
                    r"cargo check --manifest-path src-tauri/Cargo\.toml .*--locked|cargo check --manifest-path src-tauri/Cargo\.toml --locked",
                )

    def test_every_windows_lane_fails_on_lockfile_drift(self) -> None:
        expected = (
            "git diff --exit-code -- apps/desktop/pnpm-lock.yaml "
            "apps/desktop/src-tauri/Cargo.lock"
        )
        for name, text in self.workflows.items():
            with self.subTest(workflow=name):
                self.assertIn(expected, text)


if __name__ == "__main__":
    unittest.main()
