#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
ENTRY = ROOT / "scripts" / "divan-desktop-bridge.py"
PLUGIN_ROOT = ROOT / "plugins" / "sadrazam"
BUILD_ROOT = ROOT / "build" / "desktop-core"
DIST = BUILD_ROOT / "dist"
WORK = BUILD_ROOT / "work"
SPEC = BUILD_ROOT / "spec"
PROVENANCE_MODULE = BUILD_ROOT / "divan_desktop_build_info.py"
BINARIES = ROOT / "apps" / "desktop" / "src-tauri" / "binaries"


def _run_text(argv: list[str]) -> str:
    completed = subprocess.run(
        argv,
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    value = completed.stdout.strip()
    if not value:
        raise RuntimeError(f"command returned empty output: {' '.join(argv)}")
    return value


def target_triple() -> str:
    return _run_text(["rustc", "--print", "host-tuple"])


def source_provenance() -> tuple[str, str]:
    commit = _run_text(["git", "rev-parse", "HEAD"])
    tree = _run_text(["git", "rev-parse", "HEAD^{tree}"])
    for label, value in (("commit", commit), ("tree", tree)):
        if len(value) != 40 or any(char not in "0123456789abcdef" for char in value.casefold()):
            raise RuntimeError(f"invalid Git {label} SHA: {value!r}")
    return commit.casefold(), tree.casefold()


def write_provenance_module() -> None:
    commit, tree = source_provenance()
    PROVENANCE_MODULE.write_text(
        "# Generated by scripts/build_desktop_core.py; do not commit.\n"
        f"SOURCE_COMMIT = {commit!r}\n"
        f"SOURCE_TREE = {tree!r}\n",
        encoding="utf-8",
    )


def main() -> int:
    if not ENTRY.exists():
        raise FileNotFoundError(ENTRY)
    BUILD_ROOT.mkdir(parents=True, exist_ok=True)
    BINARIES.mkdir(parents=True, exist_ok=True)
    write_provenance_module()

    subprocess.run(
        [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            "--onefile",
            "--name",
            "divan-core",
            "--paths",
            str(PLUGIN_ROOT),
            "--paths",
            str(BUILD_ROOT),
            "--distpath",
            str(DIST),
            "--workpath",
            str(WORK),
            "--specpath",
            str(SPEC),
            str(ENTRY),
        ],
        cwd=ROOT,
        check=True,
    )

    extension = ".exe" if sys.platform == "win32" else ""
    source = DIST / f"divan-core{extension}"
    destination = BINARIES / f"divan-core-{target_triple()}{extension}"
    if not source.exists():
        raise FileNotFoundError(source)
    shutil.copy2(source, destination)
    print(destination.relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
